// ============================================================
// Sunroom — Supabase Database Types (Generated)
// ============================================================
// This file will be auto-generated by `supabase gen types typescript`
// once the database schema is applied. For now, it provides a
// placeholder that matches our planned schema.
// ============================================================

export interface Database {
  public: {
    Tables: {
      families: {
        Row: {
          id: string;
          name: string;
          invite_code: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          invite_code?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          invite_code?: string;
          created_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          display_name: string;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          avatar_url?: string | null;
          created_at?: string;
        };
      };
      family_members: {
        Row: {
          id: string;
          family_id: string;
          user_id: string;
          role: 'admin' | 'member' | 'senior';
          is_trusted_caller: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          user_id: string;
          role: 'admin' | 'member' | 'senior';
          is_trusted_caller?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          user_id?: string;
          role?: 'admin' | 'member' | 'senior';
          is_trusted_caller?: boolean;
          created_at?: string;
        };
      };
      devices: {
        Row: {
          id: string;
          family_id: string;
          device_name: string;
          provision_code: string | null;
          status: 'pending' | 'active' | 'offline';
          paired_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          device_name?: string;
          provision_code?: string | null;
          status?: 'pending' | 'active' | 'offline';
          paired_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          device_name?: string;
          provision_code?: string | null;
          status?: 'pending' | 'active' | 'offline';
          paired_at?: string | null;
          created_at?: string;
        };
      };
      device_telemetry: {
        Row: {
          id: string;
          device_id: string;
          family_id: string;
          battery_level: number;
          wifi_strength: number;
          status: string;
          last_seen: string;
        };
        Insert: {
          id?: string;
          device_id: string;
          family_id: string;
          battery_level: number;
          wifi_strength: number;
          status?: string;
          last_seen?: string;
        };
        Update: {
          id?: string;
          device_id?: string;
          family_id?: string;
          battery_level?: number;
          wifi_strength?: number;
          status?: string;
          last_seen?: string;
        };
      };
      call_logs: {
        Row: {
          id: string;
          family_id: string;
          caller_id: string;
          receiver_device_id: string;
          call_mode: 'regular' | 'auto_answer';
          duration_seconds: number;
          status: 'ringing' | 'answered' | 'declined' | 'missed' | 'ended';
          started_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          caller_id: string;
          receiver_device_id: string;
          call_mode: 'regular' | 'auto_answer';
          duration_seconds?: number;
          status?: 'ringing' | 'answered' | 'declined' | 'missed' | 'ended';
          started_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          caller_id?: string;
          receiver_device_id?: string;
          call_mode?: 'regular' | 'auto_answer';
          duration_seconds?: number;
          status?: 'ringing' | 'answered' | 'declined' | 'missed' | 'ended';
          started_at?: string;
        };
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
